In [8]:
import re
data = ''' 이름:김철수
전화번호 : 010-1234-1234
나이 : 30
성별 : 남
'''
p = re.compile("\d.+")
m = p.search(data)
m.group()

'010-1234-1234'

In [10]:
re.findall(r'\d+[-]\d+[-]\d+', data)

['010-1234-1234']

In [19]:
s = "black, blue and brown"
p = re.compile('.+(?=and)')
p.findall(s)

['black, blue ']

In [44]:
s= 'http://naver.com, http://google.com, ftp://daum.net'

p = re.compile('\w+(?=:)')
p.findall(s)

['http', 'http', 'ftp']

In [385]:
data = '''
안녕하세요 그리고 그리고
안녕하세요 또 또
안녕하세요 그런데 그런데 
안녕하세요 끝 끝
'''
li = []
for i in re.finditer(r'(?P<word>\w+)\s+(?P=word)', data):
    print(i.group())

그리고 그리고
또 또
그런데 그런데
끝 끝


In [73]:
import urllib.request as req
import re

# 접속 가능 여부 받기(Response 값 오는 지)
# req.urlopen("http://daum.net")

# 전체 내용 읽어오기
data = req.urlopen("http://daum.net").read().decode("utf-8")
data

In [113]:
p = re.compile("https://\S*[.]js")
li = p.findall(data)
for i in li :
    print(i)

https://t1.daumcdn.net/kas/static/na.min.js
https://t1.daumcdn.net/tiara/js/v1/tiara.min.js
https://t1.daumcdn.net/top/tiller-pc/lib/1636937121956/polyfill.min.js
https://t1.daumcdn.net/top/tiller-pc/h/production/20220915_111213/index.js
https://t1.daumcdn.net/kas/static/ba.min.js
https://t1.daumcdn.net/top/tiller-pc/1655174491872/tiller-pc-suggest.js


In [455]:
# 긁어온 웹 페이지
data = """
<div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="true" class="M_704" style="display: block;"><span class="WoYOw">이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로, 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다. </span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는 ...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다!  ...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">인절미빵. 먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요 ㅋㅋㅋ  여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">사장님 너무 친절하시고 빵이 진짜 맛있어요.. 미친 맛,,,,🥹가격이 타 빵집보다 훠얼씬 저렴한데  맛이 훠얼씬 맛있네요,,,??!?! 저희 동네에 있었음 매일 가고싶네요ㅠㅠㅠ …</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">재료를 아끼지 않으세요 눚은시간 방문했는데도 손님들이 꽤 왔어요 마늘바게트에는 소스를 아끼지 않았고 다른빵들도 크림이 듬뿍 들어 있었어요 서비스도 주시고 시식…</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div> 
"""

p = re.compile('(?=>).+?(?=<)')
li = p.findall(data)
li
for i in li :
    if i != '>' :
        print(i.replace(">", ""))

이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로, 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다. 
우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는 ...
내용 더보기
맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다!  ...
내용 더보기
인절미빵. 먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다...
내용 더보기
사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요 ㅋㅋㅋ  여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서...
내용 더보기
성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주...
내용 더보기
사장님 너무 친절하시고 빵이 진짜 맛있어요.. 미친 맛,,,,🥹가격이 타 빵집보다 훠얼씬 저렴한데  맛이 훠얼씬 맛있네요,,,??!?! 저희 동네에 있었음 매일 가고싶네요ㅠㅠㅠ …
내용 더보기
재료를 아끼지 않으세요 눚은시간 방문했는데도 손님들이 꽤 왔어요 마늘바게트에는 소스를 아끼지 않았고 다른빵들도 크림이 듬뿍 들어 있었어요 서비스도 주시고 시식…
내용 더보기


In [170]:
# 규칙에 맞는 지 확인하기 위한 정규식을 작성해보세요
# 전화번호(010-0000-0000)
# \d{2, 3}[-]\d{3, 4}[-]\d+
# 010[-]\d{4}[-]\d{4}

# 이메일(xxxxx@xxxxxx.com)
# ^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$


In [226]:
text = '''
http://www.google.com/
https://mail.google.com/
ftp://ftp.google.com/
''' 
p = re.compile(".+(?=//)")
p.findall(text)

['http:', 'https:', 'ftp:']

In [246]:
text ='''apple: $50.24
banana: $35.25
pizza: $100
''' 
p = re.compile('(?<=[$]).+') 
p.findall(text)

['50.24', '35.25', '100']

In [284]:
text = '''<p>이른 아침 문을 여는 빵집입니다</p>
<h1>아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요</h1>
<h5>이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다</h5>
<p>가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다</p>
<p>참고로 식빵 나오는 시간은 오전시시 입니다</pp>
''' 
p = re.compile("(?<=<p>).+(?=</p>)")
li = p.findall(text)
for i in li :
    print(i)

이른 아침 문을 여는 빵집입니다
가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다


In [366]:
s = "black, blue and brown"
p = re.compile("(^brown)")
p.findall(s)

[]

In [390]:
# 1차원 배열 만들기
import numpy as np
# 입력은 리스트 형식
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [393]:
# 1차원 자료.
# 튜플에 하나의 요소만 있으면 문법상 콤마를 붙인다
a.shape

(4,)

In [395]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b.shape

(2, 3)

In [396]:
a = np.array(range(20))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [399]:
a.reshape((4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [490]:
# 다음과 같은 6x6 array를 만들고 노란색 빨간색 파란색으로 뽑아보세요
a = np.array(range(25)).reshape((5, 5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [491]:
yellow = a[4:]
print(yellow)

[[20 21 22 23 24]]


In [492]:
# 전체 행 : 1 3 열
red = a[:,[1,3]]
print(red)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]]


In [493]:
# 팬시 인덱싱
blue = a[[1, 1, 3, 3], [0, 2, 0, 2]]
print(blue)

[ 5  7 15 17]


In [503]:
a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
# array 만들기
arr = np.array(a)

# 슬라이스
# 행(1~3) 열(0~2) 부분을 자르겠다
# print(arr[1:3, 0:2])
# print(arr[:1])
# print(arr[1:])
# print(arr[::2])
# print(arr[:,2])
print(arr[1:])
print(arr[1,:])

[[4 5 6]
 [7 8 9]]
[4 5 6]
