In [4]:
data = """
<head>
	<title>hello world</title>
</head>
"""

import re
p = re.compile("(?<=>).*(?=<)")
p.search(data).group()

'hello world'

In [25]:
import numpy as np

a = np.array(range(36)).reshape((6, 6))
a[:,[0, 2, 4]]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [31]:
a = np.array(range(1, 100)).reshape(3, 3, -1)
a

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]],

       [[34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]],

       [[67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
        [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [36]:
a = np.array([0,1,2,3,4,5])
b = np.array([[0],[10],[20],[30],[40],[50]])
c = a+b

yellow = c[[0, 0] ,[3, 4]]
print(yellow)

[3 4]


In [39]:
red = c[:,2]
print(red)

[ 2 12 22 32 42 52]


In [45]:
blue = c[4:, 4:,]
print(blue)

[[44 45]
 [54 55]]


In [46]:
blue_line = c[2::2, ::2]
print(blue_line)

[[20 22 24]
 [40 42 44]]


In [48]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
a[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 1,  7, 13, 19])