In [4]:
import pandas as pd
import numpy as np
import pydataset as py

mpg = py.data('mpg')

In [8]:
# 제조사 : audi, ford ,jeep, lincol 만 뽑아주세요

li = ['audi','ford','jeep','lincoln']
mpg_df_1 = mpg[mpg['manufacturer'].isin(li)]
mpg_df_1


mpg_df_2 = mpg.query("manufacturer in ['audi', 'ford', 'jeep', 'lincoln']") 

In [16]:
# 제조사 별로 drv에 따른 cty의 최대값을 sn

import seaborn as sns
drv_cty = mpg_df_1.groupby(['manufacturer', 'drv'])['cty'].max()
drv_cty = drv_cty.reset_index()
print(drv_cty)
#   manufacturer drv  cty
# 0         audi   4   20
# 1         audi   f   21
# 2         ford   4   15
# 3         ford   r   18
# 4         jeep   4   17
# 5      lincoln   r   12

  manufacturer drv  cty
0         audi   4   20
1         audi   f   21
2         ford   4   15
3         ford   r   18
4         jeep   4   17
5      lincoln   r   12


In [18]:
mpg_df_1.groupby(['manufacturer', 'drv'], as_index=False)['cty'].max()
drv_cty

manufacturer drv  cty
0         audi   4   20
1         audi   f   21
2         ford   4   15
3         ford   r   18
4         jeep   4   17
5      lincoln   r   12

문장 토큰화(sentence tokenization)은 문장의 마침표, 개행문자(\n) 등 문장의 마지막을 뜻하는 기호에 따라 분리하는 것이 일반적(492)

In [19]:
pip install nltk

     ---------------------------------------- 1.5/1.5 MB 11.9 MB/s eta 0:00:00
     -------------------------------------- 267.7/267.7 kB 8.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.1 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
# 예제 다운로드 받기
from nltk import sent_tokenize
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [21]:
text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
                You can see it out your window or on your television. \
                You feel it when you go to work, or go to church or pay your taxes'


# 문장 토큰화를 진행할 text를 sent_tokenize안에 넣어준다.
sentences = sent_tokenize(text=text_sample)
print(type(sentences), len(sentences))
print(sentences)

<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes']


### 단어 토큰화
문장을 단어로 토큰화 하는것. 기본적으로 공백, 콤마, 마침표, 개행문자 등으로 단얼르 분리하지만 정규 표현식을 이용해 다양한 유형으로 토큰화를 수행할 수 있다.

In [23]:
from nltk import word_tokenize

words = word_tokenize(text_sample)
print(type(words), len(words))
print(words)

<class 'list'> 44
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.', 'You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.', 'You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes']


word_tokenize, sent_tokenize를 조합하여 문서에 대해 모든 단어를 토큰화 

In [24]:
from nltk import word_tokenize, sent_tokenize

# 빈 리스트 생성
li = []

# text_sample을 문장별로 쪼개기
sentences = sent_tokenize(text=text_sample)

# for 문을 돌리면서 문장별로 단어 쪼개기
for sentences in sentences :
    li.append(word_tokenize(sentences))
li

[['The',
  'Matrix',
  'is',
  'everywhere',
  'its',
  'all',
  'around',
  'us',
  ',',
  'here',
  'even',
  'in',
  'this',
  'room',
  '.'],
 ['You',
  'can',
  'see',
  'it',
  'out',
  'your',
  'window',
  'or',
  'on',
  'your',
  'television',
  '.'],
 ['You',
  'feel',
  'it',
  'when',
  'you',
  'go',
  'to',
  'work',
  ',',
  'or',
  'go',
  'to',
  'church',
  'or',
  'pay',
  'your',
  'taxes']]

In [50]:
# 리스트 컴프리핸션으로

sentences = sent_tokenize(text=text_sample)
[word_tokenize(sentences) for sentences in sentences]

[['The',
  'Matrix',
  'is',
  'everywhere',
  'its',
  'all',
  'around',
  'us',
  ',',
  'here',
  'even',
  'in',
  'this',
  'room',
  '.'],
 ['You',
  'can',
  'see',
  'it',
  'out',
  'your',
  'window',
  'or',
  'on',
  'your',
  'television',
  '.'],
 ['You',
  'feel',
  'it',
  'when',
  'you',
  'go',
  'to',
  'work',
  ',',
  'or',
  'go',
  'to',
  'church',
  'or',
  'pay',
  'your',
  'taxes']]

3개의 문장을 문장별로 먼저 토큰화 했으므로 word_tokens 변수는 3개의 리스트 객체를 내포하는 리스트가 되었다. 그리고 내포된 개별 리스트 객체는 각각 문장별로 토큰화된 단어를 요소로 가지고 있다.

문장을 단어별로 토큰화 할 경우 문맥적인 의미는 무시될 수 밖에 없다. 2의 단어가 뭉쳐서 하나의 의미를 나타내는 경우를 2-gram(bi-gram)이라 하는데 이러한 것이 무시될 수 있다는 건 큰 단점이 될 것이다.

*
1-gram : uni-gram
2-gram : bi-gram
3-gram : trigram
...
n-gram

* corpus : 말뭉치, 분석의 기본 단위?


### Stop word
분석에 큰 의미가 없는 단어를 지칭한다. 가령 영어에서 is, the, a, will등 문장을 구성하는 문법 요소는 맞지만 문맥적으로는 큰 의미가 없는 단어가 이에 해당한다.이 단어는 빈번하게 텍스트에 나타나므로 이것들을 사전에 제거하지 않으면 그 빈번함으로 인해 중요한 단어로 인지 될 수 있기 때문에 이전에 제거해야한다.

In [53]:
import nltk
stopwords = nltk.download('stopwords')
print(nltk.corpus.stopwords.words('english')[:20])

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [57]:
sentences = sent_tokenize(text=text_sample)
stopwords = nltk.corpus.stopwords.words('english')

all_tokens = []
for sentence in sentences : 
    filtered_words = []
    # 개별 문장별로 토큰화된 문장 list에 대해 스톱워드를 제거하는 반복문
    for word in sentence :
        # 소문자로 변환
        word = word.lower()
        # 토큰화된 개별 단어가 스톱 워드 단어에 포함되지 않으면 word_tokens에 추가
        if word not in stopwords :
            filtered_words.append(word)
    all_tokens.append(filtered_words)
    
all_tokens

[['h',
  'e',
  ' ',
  'r',
  'x',
  ' ',
  ' ',
  'e',
  'v',
  'e',
  'r',
  'w',
  'h',
  'e',
  'r',
  'e',
  ' ',
  ' ',
  'l',
  'l',
  ' ',
  'r',
  'u',
  'n',
  ' ',
  'u',
  ',',
  ' ',
  'h',
  'e',
  'r',
  'e',
  ' ',
  'e',
  'v',
  'e',
  'n',
  ' ',
  'n',
  ' ',
  'h',
  ' ',
  'r',
  '.'],
 ['u',
  ' ',
  'c',
  'n',
  ' ',
  'e',
  'e',
  ' ',
  ' ',
  'u',
  ' ',
  'u',
  'r',
  ' ',
  'w',
  'n',
  'w',
  ' ',
  'r',
  ' ',
  'n',
  ' ',
  'u',
  'r',
  ' ',
  'e',
  'l',
  'e',
  'v',
  'n',
  '.'],
 ['u',
  ' ',
  'f',
  'e',
  'e',
  'l',
  ' ',
  ' ',
  'w',
  'h',
  'e',
  'n',
  ' ',
  'u',
  ' ',
  'g',
  ' ',
  ' ',
  'w',
  'r',
  'k',
  ',',
  ' ',
  'r',
  ' ',
  'g',
  ' ',
  ' ',
  'c',
  'h',
  'u',
  'r',
  'c',
  'h',
  ' ',
  'r',
  ' ',
  'p',
  ' ',
  'u',
  'r',
  ' ',
  'x',
  'e']]

In [61]:
sentences = sent_tokenize(text_sample)
word_tokens = [word_tokenize(sentence) for sentence in sentences]

# 영어 stopword
stopwords = nltk.corpus.stopwords.words('english')

# 문장별 단어 토큰화 + stopword 제거
all_tokens = []

for sentence in word_tokens:
    filtered_words=[]
    
    # 문장 토큰의 각 단어 토큰
    for word in sentence:
        # 소문자 변환
        word = word.lower()
        # stopword 미포함
        if word not in stopwords:
            filtered_words.append(word)
            
    all_tokens.append(filtered_words)
    
print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes']]


### Stemming과 Lemmatization
Steam : 어간
Stemming
- 어간추출
- 단어의 원형을 찾는데, 원형 단어로 변환 시 일반적인 방법을 적용하거나 더 단순화된 방법을 적용해 원래 단어에서 일부 철자가 훼손된 어근단어를 추출하는 경향이 있다.
- plays -> play

Lemmatization
- 표제어 추출
- 품사와 같은 문법적인 요소와 더 의미적인 부분을 감안해 정확한 철자로 된 어근 단어를 찾아준다.
- is, was -> be

In [62]:
# Stemming
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('plays'), stemmer.stem('playing'), stemmer.stem('played'))
print(stemmer.stem('working'), stemmer.stem('works'), stemmer.stem('worked'))
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
print(stemmer.stem('happier'),stemmer.stem('happiest'))
print(stemmer.stem('fancier'),stemmer.stem('fanciest'))

play play play
work work work
amus amus amus
happy happiest
fant fanciest


In [31]:
print(stemmer.stem('amuse'), stemmer.stem('amuses'), stemmer.stem('amused'))

amus amus amus


In [32]:
print(stemmer.stem('happier'), stemmer.stem('happiest'))

happy happiest


정확하지 못한 변환(497)

In [63]:
# Lemmatization
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()

# 책에서는 'wordnet'이였지만 바뀐듯 하다
nltk.download('omw-1.4')

# 동사: v, 형용사: a
print(lemma.lemmatize('plays', 'v'))
print(lemma.lemmatize('is', 'v'), lemma.lemmatize('was', 'v'), lemma.lemmatize('being', 'v'))
print(lemma.lemmatize('amusing','v'),lemma.lemmatize('amuses','v'),lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'),lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'),lemma.lemmatize('fanciest','a'))

play
be be be
amuse amuse amuse
happy happy
fancy fancy


[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


## Bag of Words - BOW
문서가 가지는 모든 단어(words)를 문맥이나 순서를 무시하고 일괄적으로 단어에 대해 빈도 값을 부여 한 뒤 피처 값을 추출하는 모델이다. 쉽고 빠른 구축이 가능하지만 단어의 순서를 고려하지 않으므로 문맥적인 의미 반영이 부족하고 희소 행렬(대부분의 값이 0)의 문제가 있다.

### Count 벡터화
- 단어 피처에 값을 부여할 때 각 문서에서 해당 단어가 나타나는 횟수
- 단순하게 모든 단어의 빈도로 피처 벡터화를 진행한다.
- CountVectorizer를 이용해 행은 각 문장(문서)는 
- 카운트 벡터화에서는 카운트 값이 높을 수록 중요한 단어로 인식






그것이 문서의 특징을 잘 나타낼 수 있는 단어 뿐 아니라 언어의 특성상 문장에서 자주 사용될 수 밖에 없는 단어까지 높은 값을 부여하게 되는 것이 문제이다. 이러한 문제를 보완하기 위해 TF-IDF(Term Frequency Inverse Document Frequency) 벡터화를 사용한다.

TF-IDF : 개별 문서에서 자주 나타내는 단어에 높은 가중치를 주되, 모든 문서에서 전반적으로 자주 나타나는 단어에 대해서는 페널티를 주는 방식으로 값을 부여

In [42]:
a = np.zeros((5,5))
a[4] = 1
a 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [44]:
from scipy import sparse

# 희소행렬 만들기
data = np.array([3, 1, 2])
row = np.array([0, 0, 1])
col = np.array([0, 2, 1])

# sparse 패키지의 coo_matrix를 이용해 COO형식으로 희소 행렬 생성
# coo_matrix((M, N), [dtype])
sparse_coo = sparse.coo_matrix((data, (row, col)))

In [46]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

In [47]:
# coo_matrix(D)
sparse.coo_matrix(sparse_coo.toarray()).toarray()

array([[3, 0, 1],
       [0, 2, 0]])

In [48]:
# dense2를 위처럼 생성하세요
# dense2 = np.array([[0,0,1,0,0,5],
#                   [1,4,0,3,2,5],
#                   [0,6,0,3,0,0],
#                   [2,0,0,0,0,0],
#                   [0,0,0,7,0,8],
#                   [1,0,0,0,0,0]])

# 0이 아닌 데이터
data = np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

# 행과 열 위치를 각각 배열로 생성
row = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
col = np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

# 
sparse.coo_matrix((data, (row, col))).toarray()

array([[0, 0, 1, 0, 0, 5],
       [1, 4, 0, 3, 2, 5],
       [0, 6, 0, 3, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 8],
       [1, 0, 0, 0, 0, 0]])

In [49]:
# 행 위치 배열의 고유한 값에 시작 위치 인덱스를 배열로 생성
row_index = np.array([0, 2, 7, 9, 10, 12, 13])
sparse_csr = sparse.csr_matrix((data, col, row_index))
sparse_csr.toarray()

array([[0, 0, 1, 0, 0, 5],
       [1, 4, 0, 3, 2, 5],
       [0, 6, 0, 3, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 8],
       [1, 0, 0, 0, 0, 0]])

In [ ]:
r

In [5]:
## IMDB 영화평

# 데이터 로드
import pandas as pd

review_df = pd.read_csv('./labeledTrainData.tsv', header=0, sep='\t', quoting=3)
review_df[:3]

id  sentiment                                             review
0  "5814_8"          1  "With all this stuff going down at the moment ...
1  "2381_9"          1  "\"The Classic War of the Worlds\" by Timothy ...
2  "7759_3"          0  "The film starts with a manager (Nicholas Bell...

In [6]:
review_df["review"][0]

'"With all this stuff going down at the moment with MJ i\'ve started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ\'s feeling towards the press and also the obvious message of drugs are bad m\'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally

In [7]:
import re

# <br> html 태그는 replace 함수를 사용해 공백으로 변환
review_df['review'] = review_df['review'].str.replace('<br />', ' ')
review_df['review'] = review_df['review'].apply(lambda x : re.sub("[^a-zA-Z]", " ", x))
review_df['review']

0         With all this stuff going down at the moment ...
1           The Classic War of the Worlds   by Timothy ...
2         The film starts with a manager  Nicholas Bell...
3         It must be assumed that those who praised thi...
4         Superbly trashy and wondrously unpretentious ...
                               ...                        
24995     It seems like more consideration has gone int...
24996     I don t believe they made this film  Complete...
24997     Guy is a loser  Can t get girls  needs to bui...
24998     This    minute documentary Bu uel made in the...
24999     I saw this movie as a child and it broke my h...
Name: review, Length: 25000, dtype: object

In [10]:
from sklearn.model_selection import train_test_split

class_df = y_target = review_df["sentiment"]
feature_df = X_feature = review_df.drop(['id', 'sentiment'], axis=1, inplace=False)

X_train, X_test, y_train, y_test= train_test_split(X_feature, y_target, test_size=0.3, random_state=156)

X_train.shape, X_test.shape

((17500, 1), (7500, 1))

In [12]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score

# 피처 벡터화: CountVectorizer, ML: LogisticRegression
pipeline = Pipeline([("cnt_vect", CountVectorizer(stop_words="english", ngram_range=(1,2) ) ),
                     ("LR", LogisticRegression(solver='liblinear', C=10) )
                    ])

# 학습
pipeline.fit(X_train['review'], y_train)
# 예측
pred = pipeline.predict(X_test['review'])
pred_probs = pipeline.predict_proba(X_test['review'])[:,1]
# 평가
acc = accuracy_score(y_test, pred)
auc = roc_auc_score(y_test, pred_probs)

print(f"예측 정확도: {acc:.4f}, ROC-AUC: {auc:.4f}")

예측 정확도: 0.8859, ROC-AUC: 0.9503


In [13]:
# 피처 벡터화: TfidfVectorizer, ML: LogisticRegression
pipeline = Pipeline([("tfidf_vect", TfidfVectorizer(stop_words="english", ngram_range=(1,2) ) ),
                     ("LR", LogisticRegression(C=10) )
                    ])

# 학습
pipeline.fit(X_train['review'], y_train)
# 예측
pred = pipeline.predict(X_test['review'])
pred_probs = pipeline.predict_proba(X_test['review'])[:,1]
# 평가
acc = accuracy_score(y_test, pred)
auc = roc_auc_score(y_test, pred_probs)

print(f"예측 정확도: {acc:.4f}, ROC-AUC: {auc:.4f}")

예측 정확도: 0.8936, ROC-AUC: 0.9598
