In [2]:
import numpy as np
dense = np.array([[0,1,0,3],
                  [1,2,0,0],
                  [0,0,1,0],
                  [0,2,0,0]])

In [3]:
# COO 형식
data = np.array([1, 3, 1, 2, 1, 2])
row = np.array([0, 0, 1, 1, 2, 3])
col = np.array([1, 3, 0, 1, 2, 1])

In [5]:
from scipy import sparse
sparse.coo_matrix((data, (row, col))).toarray()

array([[0, 1, 0, 3],
       [1, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 2, 0, 0]])

In [ ]:
data = [1, 3, 1, 2, 1, 2]
row_index = np.array([0, 2, 4, 5, 6])
col = [1, 3, 0, 1, 2, 1]

sparse.csr_matrix((data, col, row_index)).toarray() 

array([[0, 1, 0, 3],
       [1, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 2, 0, 0]])

In [16]:
data = np.array([1, 3, 1, 2, 1, 2])
row_index = np.array([0, 2, 4, 5, 6])
col = np.array([1, 3, 0, 1, 2, 1])

sparse.coo_matrix((data, (row, col)), (6,5)).toarray() 

array([[0, 1, 0, 3],
       [1, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 2, 0, 0]])

In [17]:
text = 'I decided, very early on, just to accept life unconditionally.\
        I never expected it to do anything special for me,\
        yet I seemed to accomplish far more than I had ever hoped.\
        Most of the time it just happened to me without my ever seeking it.' 

In [30]:
from nltk import word_tokenize, sent_tokenize
import nltk
import re

text1 = re.sub("[^a-zA-Z]", " ", text)
sent_tokenize_sentences = sent_tokenize(text1)
word_tokens = [word_tokenize(sentence) for sentence in sent_tokenize_sentences]

# 영어 stopword
stopwords = nltk.corpus.stopwords.words('english')

# 문장별 단어 토큰화 + stopword 제거
del_stopword_tokens = []

for sentence in word_tokens:
    filtered=[]
    for word in sentence:
        word = word.lower()
        if word not in stopwords:
            filtered.append(word)
            
    del_stopword_tokens.append(filtered)
    
print(del_stopword_tokens)

[['decided', 'early', 'accept', 'life', 'unconditionally', 'never', 'expected', 'anything', 'special', 'yet', 'seemed', 'accomplish', 'far', 'ever', 'hoped', 'time', 'happened', 'without', 'ever', 'seeking']]


In [32]:
text = text.lower()

# 1. 특수문자 제거
text = re.sub("[^a-zA-Z]", " ", text)

# 2. 단어 토큰화
words = word_tokenize(text)

# 3. 스톱 워드 제거
stopwords = nltk.corpus.stopwords.words('english')
words = [word for word in words if word not in stopwords]

print(words) 

['decided',
 'early',
 'accept',
 'life',
 'unconditionally',
 'never',
 'expected',
 'anything',
 'special',
 'yet',
 'seemed',
 'accomplish',
 'far',
 'ever',
 'hoped',
 'time',
 'happened',
 'without',
 'ever',
 'seeking']

In [34]:
import nltk
# NLTK의 모든 데이터 세트와 패키지를 내려 받겠다.
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\abc.zip.
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping grammars\basque_grammars.zip.
[nltk_data]   

True

In [36]:
from nltk.corpus import wordnet as wn

synsets = wn.synsets('present')

print(f'synets() 반환 type : {type(synsets)}')
print(f'synets() 반환 값 개수 : {len(synsets)}')
print(f'synets() 반환 값 : {synsets}')

synets() 반환 type : <class 'list'>
synets() 반환 값 개수 : 18
synets() 반환 값 : [Synset('present.n.01'), Synset('present.n.02'), Synset('present.n.03'), Synset('show.v.01'), Synset('present.v.02'), Synset('stage.v.01'), Synset('present.v.04'), Synset('present.v.05'), Synset('award.v.01'), Synset('give.v.08'), Synset('deliver.v.01'), Synset('introduce.v.01'), Synset('portray.v.04'), Synset('confront.v.03'), Synset('present.v.12'), Synset('salute.v.06'), Synset('present.a.01'), Synset('present.a.02')]


In [39]:
for synset in synsets :
    print('##### Synset name : ', synset.name(),'#####')
    print('POS :', synset.lexname())
    print('Definition:', synset.definition())
    print('Lemmas:', synset.lemma_names())
    print()

##### Synset name :  present.n.01 #####
POS : noun.time
Definition: the period of time that is happening now; any continuous stretch of time including the moment of speech
Lemmas: ['present', 'nowadays']

##### Synset name :  present.n.02 #####
POS : noun.possession
Definition: something presented as a gift
Lemmas: ['present']

##### Synset name :  present.n.03 #####
POS : noun.communication
Definition: a verb tense that expresses actions or states at the time of speaking
Lemmas: ['present', 'present_tense']

##### Synset name :  show.v.01 #####
POS : verb.perception
Definition: give an exhibition of to an interested audience
Lemmas: ['show', 'demo', 'exhibit', 'present', 'demonstrate']

##### Synset name :  present.v.02 #####
POS : verb.communication
Definition: bring forward and present to the mind
Lemmas: ['present', 'represent', 'lay_out']

##### Synset name :  stage.v.01 #####
POS : verb.creation
Definition: perform (a play), especially on a stage
Lemmas: ['stage', 'present', 'rep

In [44]:
# synset 객체를 단어별로 생성
tree = wn.synset('tree.n.01')
lion = wn.synset('lion.n.01')
tiger = wn.synset('tiger.n.02')
cat = wn.synset('cat.n.01')
dog = wn.synset('dog.n.01')

# 여러 객체를 하나의 리스트로 생성
entities = [tree , lion , tiger , cat , dog]

# 각 객체별 다른 객체와의 유사도 측정 후 담아줄 빈 리스트
similarities = []

# 각 객체의 이름 리스트
entity_names = [ entity.name().split('.')[0] for entity in entities]

# 단어별 synset을 반복하면서 다른 단어의 synset과 유사도를 측정
for enity in entities :
    similarity = [round(enity.path_similarity(compared_entity), 2)
                 for compared_entity in entities]
    similarities.append(similarity)
    
similarities

[[1.0, 0.07, 0.07, 0.08, 0.12],
 [0.07, 1.0, 0.33, 0.25, 0.17],
 [0.07, 0.33, 1.0, 0.25, 0.17],
 [0.08, 0.25, 0.25, 1.0, 0.2],
 [0.12, 0.17, 0.17, 0.2, 1.0]]

In [46]:
# 개별 단어별 synset과 다른 단어의 synset과의 유사도를 DataFrame형태로 저장
similarity_df = pd.DataFrame(similarities, columns=entity_names, index=entity_names)
similarity_df

tree  lion  tiger   cat   dog
tree   1.00  0.07   0.07  0.08  0.12
lion   0.07  1.00   0.33  0.25  0.17
tiger  0.07  0.33   1.00  0.25  0.17
cat    0.08  0.25   0.25  1.00  0.20
dog    0.12  0.17   0.17  0.20  1.00

In [47]:
import nltk
from nltk.corpus import sentiwordnet as swn

senti_synsets = list(swn.senti_synsets('slow'))

print(f'senti_synsets() 반환 type : {type(senti_synsets)}')
print(f'senti_synsets() 반환 값 개수 : {len(senti_synsets)}')
print(f'senti_synsets() 반환값 : {senti_synsets}')

senti_synsets() 반환 type : <class 'list'>
senti_synsets() 반환 값 개수 : 11
senti_synsets() 반환값 : [SentiSynset('decelerate.v.01'), SentiSynset('slow.v.02'), SentiSynset('slow.v.03'), SentiSynset('slow.a.01'), SentiSynset('slow.a.02'), SentiSynset('dense.s.04'), SentiSynset('slow.a.04'), SentiSynset('boring.s.01'), SentiSynset('dull.s.08'), SentiSynset('slowly.r.01'), SentiSynset('behind.r.03')]


In [49]:
import nltk
from nltk.corpus import sentiwordnet as swn

father = swn.senti_synset('father.n.01')
print('father 긍정 감성 지수: ', father.pos_score())
print('father 부정 감성 지수: ', father.neg_score())
print('father 객관성 지수: ', father.obj_score())
print()

fabulous = swn.senti_synset('fabulous.a.01')
print('fabulous 긍정 감성 지수: ',fabulous.pos_score())
print('fabulous 부정 감성 지수: ',fabulous.neg_score())
print('fabulous 객관성 지수: ', fabulous.obj_score())

father 긍정 감성 지수:  0.0
father 부정 감성 지수:  0.0
father 객관성 지수:  1.0

fabulous 긍정 감성 지수:  0.875
fabulous 부정 감성 지수:  0.125
fabulous 객관성 지수:  0.0


In [50]:
v1 = (1, 2)
v2 = (2, 5)

In [53]:
# 코사인 유사도를 구하는 사용자 함수(551p)
# v1, v2는 좌표값
def cos_simility(v1, v2) : 
    dot_product = np.dot(v1, v2)
    l2_norm = (np.sqrt(sum(np.square(v1))) * np.sqrt(sum(np.square(v2))))
    similarity = dot_product / l2_norm
    
    return similarity

cos_simility(v1, v2)

0.9965457582448796

In [54]:
from nltk.corpus import wordnet as wn

def penn_to_wn(tag):
    # 형용사
    if tag.startswith('J'):
        return wn.ADJ
    
    # 명사
    elif tag.startswith('N'):
        return wn.NOUN
    
    # 부사
    elif tag.startswith('R'):
        return wn.ADV
    # 동사
    elif tag.startswith('V'):
        return wn.VERB
    return

In [55]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import sentiwordnet as swn
from nltk import sent_tokenize, word_tokenize, pos_tag

def swn_polarity(text):
    # 감성 지수 초기화 
    sentiment = 0.0
    tokens_count = 0
    
    # 어근 추출 객체
    lemmatizer = WordNetLemmatizer()
    
    # 문장 토큰화
    raw_sentences = sent_tokenize(text) 
        
    # 분해된 문장별로 단어 토큰 -> 품사 태깅 후에 SentiSynset 생성 -> 감성 지수 합산 
    for raw_sentence in raw_sentences:
        # 각 문장별 단어 토큰화 후 품사 태깅 문장 추출 (단어와 품사 생성)
        tagged_sentence = pos_tag(word_tokenize(raw_sentence))
        
        for word , tag in tagged_sentence:
            # WordNet 기반 품사 태깅
            wn_tag = penn_to_wn(tag)
            if wn_tag not in (wn.NOUN , wn.ADJ, wn.ADV):
                continue
                
            # 어근 추출
            lemma = lemmatizer.lemmatize(word, pos=wn_tag)
            if not lemma:
                continue
            
            # 어근 추출한 단어, WordNet 기반 품사 태깅을 입력해 Synset 객체 생성
            synsets = wn.synsets(lemma , pos=wn_tag)
            
            if not synsets:
                continue
            
            # 생성된 synset 객체의 첫 번째 의미 사용
            # 같은 품사여도 여러 의미 존재할 수 있기 때문에
            synset = synsets[0]
            
            # 이용해서 SentiSynset 객체 생성
            swn_synset = swn.senti_synset(synset.name())
            
            # 긍정 감성 지수 - 부정 감성 지수로 감성 지수 계산
            sentiment += (swn_synset.pos_score() - swn_synset.neg_score())           
            tokens_count += 1
    
    if not tokens_count:
        return 0
    
    # 총 score가 0 이상일 경우 긍정(Positive) 1, 그렇지 않을 경우 부정(Negative) 0 반환
    if sentiment >= 0 :
        return 1
    
    return 0

In [57]:
## IMDB 영화평
import pandas as pd
import re
from sklearn.model_selection import train_test_split

review_df = pd.read_csv('./labeledTrainData.tsv', header=0, sep='\t', quoting=3)

review_df['review'] = review_df['review'].str.replace('<br />', ' ')
review_df['review'] = review_df['review'].apply(lambda x : re.sub("[^a-zA-Z]", " ", x))

In [60]:
review_df['preds'] = review_df['review'].apply(lambda x : swn_polarity(x))

In [65]:
y_target = review_df['sentiment'].values
preds = review_df['preds'].values

In [66]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.metrics import f1_score, roc_auc_score

def get_clf_eval(y_test, pred=None, pred_proba_po=None):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)

   
    print("오차 행렬")
    print(confusion)
    print(f"정확도: {accuracy:.4f}, 정밀도: {precision:.4f}, 재현율: {recall:.4f}, F1: {f1:.4f}")

In [67]:
get_clf_eval(y_target, pred=preds)

오차 행렬
[[7668 4832]
 [3636 8864]]
정확도: 0.6613, 정밀도: 0.6472, 재현율: 0.7091, F1: 0.6767


In [68]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

senti_analyzer = SentimentIntensityAnalyzer()
senti_scores = senti_analyzer.polarity_scores(review_df['review'][0])
print(senti_scores)

{'neg': 0.13, 'neu': 0.743, 'pos': 0.127, 'compound': -0.7943}


In [69]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

def vader_polarity(review, threshold = 0.1):    
    # VADER 객체로 감성 지수 산출
    analyzer = SentimentIntensityAnalyzer()
    scores = analyzer.polarity_scores(review)
    
    # compound 값에 기반해
    # threshold 보다 크거나 같으면 1, 그렇지 않으면 0 을 반환하도록 한다.
    agg_score = scores['compound']
    final_sentiment = 1 if agg_score >= threshold else 0
    
    return final_sentiment

In [70]:
# 각 문서별로 긍정/부정 예측
review_df['vader_preds'] = review_df['review'].apply( lambda x : vader_polarity(x, 0.1) )

In [72]:
y_target = review_df['sentiment'].values
vader_preds = review_df['vader_preds'].values

get_clf_eval(y_target, pred=vader_preds)

오차 행렬
[[ 6747  5753]
 [ 1858 10642]]
정확도: 0.6956, 정밀도: 0.6491, 재현율: 0.8514, F1: 0.7366
