## 맥스 풀링(MaxPooling2D)
앞서 conv2D로 구현한 컨볼루션 층을 통해 이미지 특징을 도출하였지만, 그 결과가 여전히 크고 복잡하면 이를 다시 한번 축소해주는 과정이 필요하다. 이 과정을 **풀링(pooling)** 또는 **서브 샘플링(sub sampling)**이라고 한다.<br><br>
pooling 기법 중 가장 많이 사용되는 방법은 맥스 풀링(max pooling)이다. 이는 정해진 구역 안에서 가장 큰 값만 다음 층으로 넘기고 나머지는 버리는 형식으로, 이 과정을 거쳐 불필요한 정보를 간추릴 수있다.
```python
MaxPooling2D(pool_size=2)
```
위에서 pool_size는 풀링 창의 크기를 정하는 것으로, 2로 정하면 전체 크기가 절반으로 줄어들게 된다.

## CNN 이해하기 좋은 사이트
[CNN Explainer : Learn Convolutional Neural Network (CNN) in your browser!](https://poloclub.github.io/cnn-explainer/)

## 상수 텐서와 변수
텐서플로에서 어떠한 작업을 하려면 텐서가 필요한데, 이 텐서를 만드려면 초기값이 필요하다. 예를 들어 모두 1이거나 0인 텐서를 만들거나, 랜덤한 분포에서 뽑은 값으로 텐서를 만들수도 있다.


In [125]:
# 상수 텐서와 변수
import tensorflow as tf
# np.ones(shape=(2,1))과 동일
x = tf.ones(shape=(2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [126]:
# np.zeros(shape=(2,1))과 동일
x = tf.zeros(shape=(2, 1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [127]:
# 랜덤 텐서
# 평균이 0이고 표준 편차가 1인 정규분포에서 뽑은 랜덤한 값으로 만든 텐서
x = tf.random.normal(shape=(3, 1), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-0.50223726]
 [-0.23869872]
 [ 0.3985008 ]], shape=(3, 1), dtype=float32)


In [128]:
# 0과 1사이의 균등분포에서 뽑은 랜덤한 값으로 만든 텐서
x = tf.random.uniform(shape=(3,1), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.5068977 ]
 [0.10039842]
 [0.4714942 ]], shape=(3, 1), dtype=float32)


넘파이 배열과 텐서플로 텐서 사이의 큰 차이점이라면, 텐서플로 텐서에는 값을 할당할 수 없다는 것이다. 즉 텐서플로의 텐서는 상수이다.

In [129]:
# 예를 들어 넘파이 배열에 값 할당하기
import numpy as np
x = np.ones(shape=(2, 2))
x[0, 0] = 0
print(x)

[[0. 1.]
 [1. 1.]]


In [ ]:
# 텐서플로우에서 동일한 작업 해보기
x = tf.ones(shape=(2, 2))
x[0, 0] = 0
# --> 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment
# --> ERROR

In [131]:
# 텐서플로 텐서의 값을 수정하고 싶다면 변수를 활용하면 된다.
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.00253003],
       [0.04396727],
       [0.02358736]], dtype=float32)>


In [132]:
# 변수의 상태는 assign 메서드로 수정할 수 있다
v.assign(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [133]:
# 변수의 일부 원소에만 적용하는 것도 가능
v[0, 0].assign(3)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [134]:
# assign_add() : =+
# assign_sub() : -=
# 와 동일한 작업을 한다.
v.assign_add(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

## 텐서 연산
넘파이와 마찬가지로 텐서플로에서도 수학공식을 표현하기 위해 많은 텐서 연산을 제공한다. 몇가지 기본적인 수학 연산들을 살펴보자면

In [135]:
a = tf.ones((2, 2))
# 제곱
b = tf.square(a)
# 제곱근
c = tf.sqrt(a)
# 두 텐서를 원소별연산으로 더한다
d = b+c
# 두 텐서의 점곱을 계산
e = tf.matmul(a, b)
# 두 텐서를 연소별 연산으로 곱한다
e *= d

print(a, '\n', b, '\n', c, '\n', d, '\n', e, '\n')

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32) 
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32) 
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32) 
 tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32) 
 tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32) 



## GradientTapeAPI 다시 살펴보기
numpy는 할수 없고 tensorflow는 할수 있는 것이라면, 텐서플로는 미분 가능한 표현이라면 어떤 입력에 대해서도 그레이디언트를 계산할 수 있다는 것이다. GradientTape 블록을 시작하고 하나 또는 여러 입력 텐서에 대해 계산을 수행한 후 입력에 대한 결과의 그레이디언트를 구하면 된다

In [136]:
# GradientTape 사용하기
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape :
  result = tf.square(input_var)

# 가중치에 대한 모델 손실의 그레이디언트를 계산하는데 가장 널리 사용되는 방법
gradient = tape.gradient(result, input_var)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


모든 텐서에 대한 그래이디언트를 계산하기 위해 필요한 정보를 미리 앞서서 저장하는 것은 너무 많은 비용이 들기 때문에, 자원 낭비를 막기 위해서는 테이프가 감시할 대상을 알아야한다. 훈련 가능한 변수는 기본적으로 감시 대상이다. 훈련 가능한 변수에 대한 손실 그레이디언트를 계산하는 것이 그레이디언트 테이프의 주 사용 용도이기 때문이다.

In [137]:
# 상수 텐서 입력과 함께 GradientTape 사용하기
input_const = tf.constant(3.)
with tf.GradientTape() as tape :
  tape.watch(input_const)
  result = tf.square(input_const)

gradient = tape.gradient(result, input_const)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


그레이디언트 테이프는 강력한 유틸리티이다. 심지어는 그레이디언트의 그레이디언트(이계도 그레이언트)도 계산해볼 수 있다. 예를 들어 시간에 대한 물체 위치의 그레이디언트는 물체의 속도고, 이계도 그레이디언트는 가속도이다.

In [138]:
# 예를 들어
# 수직방향으로 낙하나는 사과의 위치를 시간에 따라 측정하고
# `position(time) = 4.9 * time **2` 임을 알았다면 가속도는 얼마일까
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape :
  with tf.GradientTape() as inner_tape :
    position = 49 * time **2
  speed = inner_tape.gradient(position, time)

# 바깥쪽 테이프가 안쪽 테이프의 그레이디언트를 계산한다
# 계산된 가속도는 4.9 * 2 = 9.8 이다.
acceleration = outer_tape.gradient(speed, time)
print(acceleration)

tf.Tensor(98.0, shape=(), dtype=float32)
